// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAMv8XY725LIguPtUMU3nlYmDo4SA331g',
    appId: '1:572737400528:web:0055579d75d7aa8746f8d5',
    messagingSenderId: '572737400528',
    projectId: 'flutter-project-c8168',
    authDomain: 'flutter-project-c8168.firebaseapp.com',
    storageBucket: 'flutter-project-c8168.firebasestorage.app',
    measurementId: 'G-STDCP2LZML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCod5yhw4tIsa5YWc18NK3htJoYcXfmvXM',
    appId: '1:572737400528:android:746f88a26573bbdf46f8d5',
    messagingSenderId: '572737400528',
    projectId: 'flutter-project-c8168',
    storageBucket: 'flutter-project-c8168.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyY5gntitEIVQrSMOaMVQ00MPUvSM_03g',
    appId: '1:572737400528:ios:c31df355fca36b4146f8d5',
    messagingSenderId: '572737400528',
    projectId: 'flutter-project-c8168',
    storageBucket: 'flutter-project-c8168.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyY5gntitEIVQrSMOaMVQ00MPUvSM_03g',
    appId: '1:572737400528:ios:c31df355fca36b4146f8d5',
    messagingSenderId: '572737400528',
    projectId: 'flutter-project-c8168',
    storageBucket: 'flutter-project-c8168.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAMv8XY725LIguPtUMU3nlYmDo4SA331g',
    appId: '1:572737400528:web:90b9028d227eea1e46f8d5',
    messagingSenderId: '572737400528',
    projectId: 'flutter-project-c8168',
    authDomain: 'flutter-project-c8168.firebaseapp.com',
    storageBucket: 'flutter-project-c8168.firebasestorage.app',
    measurementId: 'G-1G1Q3SL902',
  );
  
}
